package PageObjects.EisModel;

import org.openqa.selenium.By;

public interface EisSharedLocatorModel {
  public By POLICY_LIST();

  public By VIEW_ALL_POLICIES();

  public By POLICY_NUMBER();

  public By POLICY_TAB();

  public By INSURED_TAB();

  public By CANCEL_BUTTON();

  public By RISK_ADDRESS_TAB();

  public By CLAIMS_TAB();

  public By INTERESTED_PARTIES_TAB();

  public By LIST_POLICY_IN_TABLE();

  public By SELECT_POLICY_FROM_TABLE();

  public By COVER_OPTIONS_TAB();

  public By LIST_OPTIONAL_EXTRAS();

  public By SPECIFY_ITEMS_AWAY_FROM_HOME();

  public By LIST_OPTIONAL_EXTRAS_TABLE_COLUMN();

  public By COVER_TYPES_TAB();

  //public By COVERAGE_AND_PREMIUM_TAB();
  public By SPECIFIED_ITEMS_TAB();

  public By SPECIFIED_ITEMS_AT_HOME_TAB();

  public By SPECIFIED_ITEMS_AWAY_FROM_HOME_TAB();

  public By ENDORSEMENTS_TAB();

  public By POLICY_START_DATE();

  public By POLICY_END_DATE();

  public By INSURED_TITLE();

  public By INSURED_FIRSTNAME();

  public By INSURED_LASTNAME();

  public By INSURED_DATE_OF_BIRTH();

  public By INSURED_CORRESPONDENCE_ADDRESS_HOUSE_NO();

  public By INSURED_CORRESPONDENCE_ADDRESS_LINE1();

  public By INSURED_CORRESPONDENCE_ADDRESS_LINE2();

  public By INSURED_CORRESPONDENCE_ADDRESS_CITY();

  public By INSURED_CORRESPONDENCE_ADDRESS_COUNTY();

  public By INSURED_CORRESPONDENCE_ADDRESS_POSTCODE();

  public By INSURED_EMAIL();

  public By INSURED_EMPLOYMENT_STATUS();

  public By INSURED_EMPLOYMENT_OCCUPATION();

  public By INSURED_RISK_ADDRESS_HOUSE_NO();

  public By INSURED_RISK_ADDRESS_LINE1();

  public By INSURED_RISK_ADDRESS_LINE2();

  public By INSURED_ADDRESS_CITY();

  public By INSURED_ADDRESS_COUNTY();

  public By INSURED_ADDRESS_POSTCODE();

  public By OWNERSHIP_TYPE();

  public By PROPERTY_LET_SUBLET_STATUS();

  public By BUILDING_WORK();

  public By GOOD_REPAIR();

  public By CONSTRUCTION_TYPE();

  public By INSURED_PHONE_NO();

  public By INSURED_ADDRESS_EXTENSION();

  public By INTRUDER_ALARM_DETAILS();

  public By DOOR_LOCK_DETAILS();

  public By NUMBER_OF_ADULTS();

  public By NUMBER_OF_CHILDREN();

  public By HOUSE_OCCUPANCY();

  public By PAYING_GUEST_DETAILS();

  public By PET_DETAILS();

  public By BUSINESS_USE();

  public By NUMBER_OF_BEDROOMS();

  public By NUMBER_OF_BATHROOMS();

  public By PROPERTY_TYPE();

  public By CONSTRUCTION_YEAR();

  public By BUILDING_LISTED_DETAILS();

  public By BUILDING_ACCIDENTAL_DAMAGE_COVER();

  public By BUILDING_COST();

  public By PREVIOUS_INSURANCE_HELD();

  public By MAX_LIMIT_AMOUNT();

  public By CONTENT_ACCIDENTAL_DAMAGE_COVER();

  public By CONTENT_SUM_INSURED();

  public By INDIVIDUAL_ITEM_COVER();

  public By PERSONALISED_ITEMS_AWAY_FROM_HOME();

  public By PERSONALISED_ITEMS_AWAY_FROM_HOME_COST();

  public By HOUSEHOLD_COVER();

  public By BUILDING_VOLUNTARY_EXCESS();

  public By CONTENT_VOLUNTARY_EXCESS();

  public By SELECT_NAMED_INSURED();

  public By GET_COVER_TYPE();

  public By COVER_START_DATE();

  public By LIST_NAME_INSURED();

  public By NAME_INSURED_DROPDOWN_SELECTOR();

  public By SELECT_JOINT_POLICYHOLDER();

  public By SELECT_MAIN_POLICYHOLDER();

  public By JPH_DATE_OF_BIRTH();

  public By JPH_EMPLOYMENT_STATUS();

  public By JPH_EMPLOYMENT_INDUSTRY();

  public By JPH_FIRSTNAME();

  public By JPH_LASTNAME();

  public By JPH_MARITAL_STATUS();

  public By JPH_OCCUPATION();

  public By JPH_RELATIONSHIP_TO_PROPOSER();

  public By SECOND_EMPLOYMENT_STATUS();

  public By JPH_TITLE();

  public By CORRESPONDENCE_FULL_ADDRESS();

  public By RISK_FULL_ADDRESS();

  public By BUILDING_CONSTRUCTION();

  public By MISSING_FIELD_INFO_ERROR_MESSAGE();

  public By GET_POLICY_INFORMATION_LABEL();

  public By GET_MOTOR_POLICY_INFORMATION_VALUE();

  public By DRIVER_TAB();

  public By CLAIMS_CONVICTION_SUMMARY_TAB();

  public By UNSPENT_CRIMINAL_CONVICTION();

  public By VEHICLE_TAB();

  public By PREMIUM_COVERAGES_TAB();

  public By COVERAGE_AND_PREMIUM_TAB();

  //Motor
  public By LIST_OF_DRIVERS();

  public By DRIVER_CHANGE_LINK_DRIVER();

  // public By ADD_DRIVER_CHANGE_LINK_DRIVER();
  public By TEMP_DRIVER();

  public By DRIVER_NAME();

  public By DRIVER_TYPE();

  public By RESIDENCE_IN_UK_SINCE();

  public By PREFERRED_DELIVERY();

  public By FCA_CLASS();

  public By LICENCE_TYPE();

  public By LICENCE_OBTAIN_DATE();

  public By HELD_DRIVING_LICENCE();

  public By ACCESS_TO_OTHER_DRIVER();

  public By ACCESS_TO_ANY_OTHER_VEHICLE();

  //ADDITIONAL_DRIVER();

  public By ADD_DRIVER_RELATIONSHIP_TO_PROPOSER();

  public By ADD_DRIVER_DATE_OF_BIRTH();

  public By ADD_DRIVER_GENDER();

  public By ADD_DRIVER_MARITAL_STATUS();

  public By ADD_DRIVER_PRIMARY_EMPLOYMENT_STATUS();

  public By ADD_DRIVER_PRIMARY_OCCUPATION();

  public By ADD_DRIVER_PRIMARY_INDUSTRY();

  public By ADD_DRIVER_SECONDARY_EMPLOYMENT_STATUS();

  public By SECONDARY_EMPLOYMENT_STATUS_FLAG();

  public By ADD_DRIVER_SECONDARY_EMPLOYER_OCCUPATION();

  public By ADD_DRIVER_SECONDARY_EMPLOYMENT_INDUSTRY();

  public By ADD_DRIVER_RESIDENCE_IN_UK_SINCE();

  public By ADD_DRIVER_LICENSE_TYPE();

  public By ADD_DRIVER_LICENCE_OBTAIN_DATE();

  public By ADD_DRIVER_HELD_DRIVING_LICENCE();

  public By LICENCE_NUMBER();

  public By ADD_DRIVER_ACCESS_TO_OTHER_DRIVER();

  public By RISK_ADDRESS_SAME_AS_CORRESPONDENCE_FLAG();

  public By PRIMARY_RESIDENCE();

  public By OCCUPANCY_TYPE();

  public By PROPERTY_LEFT_UNOCCUPIED();

  public By NEIGHBOURHOOD_WATCH();

  public By NON_FAMILY_LODGER();

  public By BRUSH_FIRE_SURCHARGE();

  public By FREE_SUBSIDENCE_LANDSLIP();

  public By BUILDING_TYPE();

  public By HOUSE_TYPE();

  public By FREE_FROM_FLOODING();

  public By WALL_CONSTRUCTION();

  public By ROOF_CONSTRUCTION();

  public By FLAT_ROOF_PERCENTAGE();

  public By FULL_ACCIDENTAL_COVER_BUILDING();

  public By BUILDING_NCD();

  public By CONTENT_NCD();

  public By REBUILDING_COST();

  public By FULL_ACCIDENTAL_COVER_ON_CONTENT_VAR();

  public By SAFE_INSTALLED();

  public By UNSPECIFIED_TEMS_AWAY_FROM_HOME();

  public By VALUABLE_IN_HOME_FLAG();
  public By VALUABLE_IN_HOME();

  public By VALUABLE_AWAY_HOME_FLAG();

  public By BICYCLE_FLAG();

  public By ENDORSEMENT_LIST();

  public By INSURANCE_TYPES();

  public By LIST_OF_INSURED_HOLDERS();

  public By CREDIT_CARD_LINK();

  public By SECOND_EMPLOYMENT_FLAG();

  public By SECOND_EMPLOYMENT_OCCUPATION();

  public By SECOND_EMPLOYMENT_INDUSTRY();

  public By ITEMS_IN_HOME_LIST();

  public By ITEMS_AWAY_FROM_HOME_LIST();

  public By BICYCLE_AWAY_FROM_HOME_LIST();

  public By SPECIFIED_ITEMS_AWAY_FROM_HOME_DESCRIPTION();

  public By SPECIFIED_ITEMS_AWAY_FROM_HOME();

  public By SPECIFIED_ITEM_VALUE_AWAY_FROM_HOME();

  public By SPECIFIED_ITEM_VALUE_IN_HOME();
  public By SPECIFIED_ITEMS_SUM_INSURED();

  public By ITEM_CHANGE_LINK();

  public By CLAIMS_LIST();

  public By CLAIM_INCIDENT_SOURCE();

  public By CLAIM_INCIDENT_DATE();

  public By CLAIM_CLAIM_STATUS();

  public By CLAIM_TYPE();

  public By CLAIM_CAUSE();

  public By CLAIM_COST();

  public By CLAIM_NUM();

  public By SUFFERED_LOSS_NOT_RESULTED_CLAIM();

  public By BICYLCLE_TYPE();

  public By BICYLCLE_DESCRIPTION();

  public By BICYLCLE_VALUE();

  public By SPECIFIED_ITEMS_IN_HOME_DESCRIPTION();

  public By SPECIFIED_ITEMS_IN_HOME();

  public By BUNGLOW_TYPE();
}
